import { Shield, Eye, Lock, AlertTriangle, Users, Database, UserCheck, Search, Heart } from 'lucide-react'

function Principle({ icon: Icon, color, title, children }) {
  return (
    <div className="card">
      <div className="flex items-start gap-3 mb-2">
        <div className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${color}`}>
          <Icon className="w-4 h-4" />
        </div>
        <h3 className="text-sm font-semibold text-white pt-1">{title}</h3>
      </div>
      <p className="text-sm text-slate-300 leading-relaxed pl-11">{children}</p>
    </div>
  )
}

export default function ResponsibleAI() {
  return (
    <div className="max-w-3xl space-y-5">
      {/* Banner */}
      <div className="card bg-gradient-to-r from-amber-900/30 to-slate-800 border-amber-700/50">
        <div className="flex items-center gap-3 mb-2">
          <Shield className="w-6 h-6 text-amber-400" />
          <h1 className="text-xl font-bold text-white">Responsible AI</h1>
        </div>
        <p className="text-sm text-slate-300">
          AirGuard is designed as a student educational project. We are committed to transparent,
          fair, and honest use of AI. This page documents the limitations, assumptions, and ethical
          considerations of the system.
        </p>
      </div>

      {/* Core disclaimer */}
      <div className="bg-amber-950/50 border border-amber-700/60 rounded-xl p-4 text-sm text-amber-200 space-y-2">
        <p className="font-semibold text-amber-300">⚠️ Important Disclaimer</p>
        <p>AirGuard results are generated by a statistical AI model. They represent patterns in data and should <strong>not</strong> be used as a substitute for:</p>
        <ul className="list-disc list-inside space-y-1 text-amber-300/80">
          <li>Official government air-quality monitoring or AQI advisories</li>
          <li>Professional environmental or health assessments</li>
          <li>Regulatory compliance decisions</li>
          <li>Medical advice of any kind</li>
        </ul>
      </div>

      {/* Principles grid */}
      <div className="grid md:grid-cols-2 gap-4">
        <Principle icon={Eye} color="bg-sky-500/20 text-sky-400" title="Transparency">
          AirGuard explains why a record is flagged — the anomaly score is shown alongside each event.
          The algorithm (Isolation Forest), features used, and severity thresholds are all documented.
          No "black box" decisions are hidden from the user.
        </Principle>

        <Principle icon={Users} color="bg-green-500/20 text-green-400" title="Fairness">
          The model is trained on the user-uploaded dataset itself and makes no assumptions about
          specific communities or locations. No demographic data is collected or used.
          Results depend on the quality and representativeness of the input data.
        </Principle>

        <Principle icon={Lock} color="bg-purple-500/20 text-purple-400" title="Privacy">
          AirGuard uses only environmental sensor data. No personal or sensitive personal information
          is collected. Session data is stored in your browser's sessionStorage and deleted when
          the browser tab is closed. No data is sent to third parties.
        </Principle>

        <Principle icon={AlertTriangle} color="bg-yellow-500/20 text-yellow-400" title="False Positives">
          The Isolation Forest model may flag normal sensor readings as anomalies, particularly
          during sudden but legitimate weather changes or sensor warm-up periods. The contamination
          parameter controls how many anomalies the model expects — a too-high setting increases
          false positives. Always verify flagged events with additional context.
        </Principle>

        <Principle icon={Search} color="bg-orange-500/20 text-orange-400" title="False Negatives">
          Some genuine pollution events may not be detected — especially gradual increases that
          stay within the range of previously seen values, or events too brief to meet the minimum
          anomaly count threshold. AirGuard is a decision-support tool, not a replacement for
          continuous official monitoring.
        </Principle>

        <Principle icon={Database} color="bg-red-500/20 text-red-400" title="Data Quality">
          The accuracy of AirGuard's results depends entirely on the quality of the input data.
          Faulty sensors, miscalibration, or inconsistent timestamps can produce incorrect anomaly
          detections. The preprocessing pipeline flags and handles common data issues but cannot
          correct systematic sensor errors.
        </Principle>

        <Principle icon={UserCheck} color="bg-teal-500/20 text-teal-400" title="Human Oversight">
          AI-detected events should be reviewed by a knowledgeable human before any consequential
          decision is made. The system provides information and patterns; humans must interpret
          context, verify findings, and determine appropriate responses.
        </Principle>

        <Principle icon={Search} color="bg-pink-500/20 text-pink-400" title="Source Attribution">
          AirGuard cannot identify the source of a pollution event from sensor data alone. The AI
          explanation lists possible contributing factors as examples only. Statements like "traffic
          caused this event" are never made without sufficient evidence. Attribution requires ground-truth
          investigation beyond what this system provides.
        </Principle>
      </div>

      {/* Severity classification clarification */}
      <div className="card space-y-3">
        <h2 className="text-sm font-semibold text-white flex items-center gap-2">
          <AlertTriangle className="w-4 h-4 text-yellow-400" />
          Severity Categories — Custom, Not Official
        </h2>
        <p className="text-sm text-slate-300">
          AirGuard's severity labels (NORMAL, MODERATE, HIGH, SEVERE) are custom categories
          defined for this educational system based on the AI anomaly score and WHO-informed PM2.5
          thresholds. They are <strong className="text-yellow-300">not</strong> equivalent to or
          endorsed by the US EPA AQI, CPCB, or any official government classification system.
        </p>
        <div className="overflow-x-auto rounded border border-slate-700">
          <table className="text-xs w-full">
            <thead className="bg-slate-800">
              <tr>
                <th className="text-left px-3 py-2 text-slate-400">Label</th>
                <th className="text-left px-3 py-2 text-slate-400">Anomaly Score</th>
                <th className="text-left px-3 py-2 text-slate-400">Max PM2.5</th>
                <th className="text-left px-3 py-2 text-slate-400">Note</th>
              </tr>
            </thead>
            <tbody className="text-slate-300">
              <tr className="border-t border-slate-700/50">
                <td className="px-3 py-2"><span className="badge-normal px-2 py-0.5 rounded text-xs font-semibold">NORMAL</span></td>
                <td className="px-3 py-2">&lt; 0.40</td>
                <td className="px-3 py-2">≤ 25 µg/m³</td>
                <td className="px-3 py-2 text-slate-400">Within recent baseline</td>
              </tr>
              <tr className="border-t border-slate-700/50">
                <td className="px-3 py-2"><span className="badge-moderate px-2 py-0.5 rounded text-xs font-semibold">MODERATE</span></td>
                <td className="px-3 py-2">0.40 – 0.59</td>
                <td className="px-3 py-2">26–55 µg/m³</td>
                <td className="px-3 py-2 text-slate-400">Noticeably above baseline</td>
              </tr>
              <tr className="border-t border-slate-700/50">
                <td className="px-3 py-2"><span className="badge-high px-2 py-0.5 rounded text-xs font-semibold">HIGH</span></td>
                <td className="px-3 py-2">0.60 – 0.79</td>
                <td className="px-3 py-2">56–150 µg/m³</td>
                <td className="px-3 py-2 text-slate-400">Significantly elevated</td>
              </tr>
              <tr className="border-t border-slate-700/50">
                <td className="px-3 py-2"><span className="badge-severe px-2 py-0.5 rounded text-xs font-semibold">SEVERE</span></td>
                <td className="px-3 py-2">≥ 0.80</td>
                <td className="px-3 py-2">&gt; 150 µg/m³</td>
                <td className="px-3 py-2 text-slate-400">Substantially above baseline</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p className="text-xs text-slate-500">
          Reference for threshold guidance: WHO Global Air Quality Guidelines (2021).
          These thresholds are informational only.
        </p>
      </div>

      {/* Health information */}
      <Principle icon={Heart} color="bg-rose-500/20 text-rose-400" title="Health Information">
        AirGuard provides general environmental awareness about air pollution. It does not provide
        personalised medical advice, diagnosis, or treatment recommendations. If you have respiratory
        or cardiovascular concerns, please consult a qualified healthcare professional. During high-pollution
        events, refer to guidance from your local public health authority.
      </Principle>
    </div>
  )
}
